apiVersion: v1
kind: Service
metadata:
  name: web-disable-escalation
spec:
  selector:
    run: web-disable-escalation
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web-disable-escalation
  name: web-disable-escalation
spec:
  containers:
  - image: mochizuki875/training-website-poc:v1.0
    name: web
    securityContext:
      allowPrivilegeEscalation: false
