apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web-insecure
  name: web-insecure
spec:
  containers:
  - image: mochizuki875/training-website-poc:v1.0
    name: web
    securityContext:
      privileged: true