apiVersion: v1
kind: Service
metadata:
  name: web-insecure
spec:
  selector:
    run: web-insecure
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web-insecure
  name: web-insecure
spec:
  containers:
  - image: mochizuki875/training-website-poc:v1.0
    name: web
    securityContext:
      privileged: true
  nodeSelector:
    kubernetes.io/hostname: k8s-cluster1-worker02
