apiVersion: v1
kind: Service
metadata:
  name: web-measured
spec:
  selector:
    run: web-measured
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web-measured
  name: web-measured
spec:
  containers:
  - image: mochizuki875/training-website-poc:v2.0
    name: web
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    volumeMounts:
    - name: log-volume
      mountPath: /usr/local/apache2/logs/
  volumes:
  - name: log-volume
    emptyDir: {}
