apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web-secure
  name: web-secure
spec:
  securityContext:
      seccompProfile: 
        type: RuntimeDefault
  automountServiceAccountToken: false
  containers:
  - image: mochizuki875/training-website-poc:v2.0
    name: web
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - all
        add:
        - CHOWN
        - SETUID
        - SETGID
        - NET_BIND_SERVICE
    resources:
      limits:
        cpu: "500m"
        memory: "128Mi"
    volumeMounts:
    - name: log-volume
      mountPath: /usr/local/apache2/logs/
  volumes:
  - name: log-volume
    emptyDir: {}